name: entlz-6a-platform-connectivity-vnethubspoke
 

# Controls when the action will run. 
on:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      entlzprefix: 
        description: 'entlzprefix'
        required: true
        default: ''
      environment: 
        description: 'environment'
        required: true
        default: 'azureusgovernment'
      location: 
        description: 'location'
        required: true
        default: 'usgovvirginia'
      bastionsubnetprefix:
        description: ''
        required: true
        default: ''
      connectivitysubid:
        description: ''
        required: true
        default: ''
      fwmanagementsubnetprefix:
        description: ''
        required: true
        default: ''
      fwsubnetprefix:
        description: ''
        required: true
        default: ''
      fwtype: 
        description: ''
        required: true
        default: 'Standard'
      gwsubnetprefix:
        description: ''
        required: true
        default: ''
      gwtype:
        description: ''
        required: true
        default: ''
      hubmanagementsubnetprefix:
        description: ''
        required: true
        default: ''
      hubvnetprefix:
        description: ''
        required: true
        default: ''
      managementsubid:
        description: ''
        required: true
        default: ''
      managementsubnetprefix:
        description: ''
        required: true
        default: ''
      managementvnetprefix:
        description: ''
        required: true
        default: ''
      identitysubid:
        description: ''
        required: true
        default: ''
      identitysubnetprefix:
        description: ''
        required: true
        default: ''
      identityvnetprefix: 
        description: ''
        required: true
        default: ''
      logaworkspaceid:
        description: ''
        required: true
        default: ''
      connectivitysubid:
        description: ''
        required: true
        default: ''
      securitysubid:
        description: ''
        required: true
        default: ''
      securitysubnetprefix:
        description: ''
        required: true
        default: ''
      securityvnetprefix:
        description: ''
        required: true
        default: ''
     
#  push:
#    branches:
#      - dev
#    paths:
#      - 'templates/entlz/platform-connectivity-vnethubspoke**'
#      - '.github/workflows/entlz-6a-platform-connectivity-vnethubspoke.yml'

env:
  entlzprefix: ${{ github.event.inputs.entlzprefix }}
  environment: ${{ github.event.inputs.environment }}
  location: ${{ github.event.inputs.location }}
  bastionsubnetprefix: ${{ github.event.inputs.bastionsubnetprefix }}
  connectivitysubid:  ${{ github.event.inputs.connectivitysubid }}
  fwmanagementsubnetprefix: ${{ github.event.inputs.fwmanagementsubnetprefix }}
  fwsubnetprefix: ${{ github.event.inputs.fwsubnetprefix }}
  fwtype: ${{ github.event.inputs.fwtype }}
  gwsubnetprefix: ${{ github.event.inputs.gwsubnetprefix }}
  gwtype: ${{ github.event.inputs.gwtype }}
  hubmanagementsubnetprefix: ${{ github.event.inputs.hubmanagementsubnetprefix }}
  hubvnetprefix: ${{ github.event.inputs.hubvnetprefix }}
  identitysubid: ${{ github.event.inputs.identitysubid }}
  identitysubnetprefix: ${{ github.event.inputs.identitysubnetprefix }}
  identityvnetprefix:   ${{ github.event.inputs.identityvnetprefix }}
  logaworkspaceid: ${{ github.event.inputs.logaworkspaceid }}
  managementsubid: ${{ github.event.inputs.managementsubid }}
  managementsubnetprefix: ${{ github.event.inputs.managementsubnetprefix }}
  managementvnetprefix: ${{ github.event.inputs.managementvnetprefix }}
  securitysubid: ${{ github.event.inputs.securitysubid }}
  securitysubnetprefix: ${{ github.event.inputs.securitysubnetprefix }}
  securityvnetprefix: ${{ github.event.inputs.securityvnetprefix }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
          
        steps:
        - uses: actions/checkout@v2
        - name: Branch name
          run: echo running on branch ${GITHUB_REF##*/}       
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Deploy Connectivity Components
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              bastionsubnetprefix="${{ env.bastionsubnetprefix }}"
              connectivitysubid="${{ env.connectivitysubid }}"
              entlzprefix="${{ env.entlzprefix }}"
              environment="${{ env.environment }}"
              fwmanagementsubnetprefix="${{ env.fwmanagementsubnetprefix }}"
              fwsubnetprefix="${{ env.fwsubnetprefix }}"
              fwtype="${{ env.fwtype }}"
              gwsubnetprefix="${{ env.gwsubnetprefix }}"
              gwtype="${{ env.gwtype }}"
              hubmanagementsubnetprefix="${{ env.hubmanagementsubnetprefix}}"
              hubvnetprefix="${{ env.hubvnetprefix }}"
              identitysubid="${{ env.identitysubid }}"
              identitysubnetprefix="${{ env.identitysubnetprefix }}"
              identityvnetprefix="${{ env.identityvnetprefix }}"
              location="${{ env.location }}"
              managementsubid="${{ env.managementsubid }}"
              managementsubnetprefix="${{ env.managementsubnetprefix }}"
              managementvnetprefix="${{ env.managementvnetprefix }}"
              securitysubid="${{ env.securitysubid }}"
              securitysubnetprefix="${{ env.securitysubnetprefix }}"
              securityvnetprefix="${{ env.securityvnetprefix }}"
              logaworkspaceid="${{ env.logaworkspaceid }}"

              az deployment mg create \
                  --name "${entlzprefix}-connectivity-${location}" \
                  --management-group-id $entlzprefix \
                  --location $location \
                  --template-file "templates/entlz/platform-connectivity-vnethubspoke/platform-connectivity-vnethubspoke.bicep" \
                  --parameters \
                    bastionsubnetprefix="${bastionsubnetprefix}" \
                    connectivitysubid="${connectivitysubid}" \
                    entlzprefix="${entlzprefix}" \
                    environment="${environment}" \
                    fwmanagementsubnetprefix="${fwmanagementsubnetprefix}" \
                    fwsubnetprefix="${fwsubnetprefix}" \
                    fwtype="${fwtype}" \
                    gwsubnetprefix="${gwsubnetprefix}" \
                    gwtype="${gwtype}" \
                    hubmanagementsubnetprefix="${hubmanagementsubnetprefix}" \
                    hubvnetprefix="${hubvnetprefix}" \
                    identitysubid="${identitysubid}" \
                    identitysubnetprefix="${identitysubnetprefix}" \
                    identityvnetprefix="${identityvnetprefix}" \
                    location="${location}" \
                    managementsubid="${managementsubid}" \
                    managementsubnetprefix="${managementsubnetprefix}" \
                    managementvnetprefix="${managementvnetprefix}" \
                    securitysubid="${securitysubid}" \
                    securitysubnetprefix="${securitysubnetprefix}" \
                    securityvnetprefix="${securityvnetprefix}" \
                    logaworkspaceid="${logaworkspaceid}"