name: entlz-3-platform-management

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      entlzprefix: 
        description: 'entlzprefix'
        required: true
        default: ''
      environment: 
        description: 'environment'
        required: true
        default: 'azureusgovernment'
      location: 
        description: 'location'
        required: true
        default: 'usgovvirginia'
      managementsubid:
        description: ''
        required: true
        default: ''
      uniqueid:
        description: ''
        required: false
        default: ''      
      
#  push:
#    branches:
#      - dev
#    paths:
#      - 'templates/entlz/platform-management.bicep'
#      - 'templates/entlz/modules/**'
#      - '.github/workflows/entlz-3-platform-management.yml'

env:
  entlzprefix: ${{ github.event.inputs.entlzprefix }}
  environment: ${{ github.event.inputs.environment }}
  location: ${{ github.event.inputs.location }} 
  managementsubid: ${{ github.event.inputs.managementsubid }} 
  uniqueid: ${{ github.event.inputs.uniqueid }} 

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
          
        steps:
        - uses: actions/checkout@v2
        - name: Branch name
          run: echo running on branch ${GITHUB_REF##*/}      
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Deploy Management Components
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              # Deploy Management Components to Management Subscription
                az deployment sub create \
                  --name "${{ env.entlzprefix }}-management-${{ env.location }}" \
                  --subscription "${{ env.managementsubid }}" \
                  --location "${{ env.location }}" \
                  --template-file "templates/entlz/platform-management.bicep" \
                  --parameters entlzprefix=${{ env.entlzprefix }} uniqueid=${{ env.uniqueid }}