name: entlz-6a-platform-connectivity-vnethubspoke
env:
  entlzprefix: entlz
  environment: azureusgovernment
  location: usgovvirginia
  bastionsubnetprefix:
  connectivitysubid:
  fwmanagementsubnetprefix:
  fwsubnetprefix:
  fwtype: Standard
  gwsubnetprefix:
  gwtype:
  hubmanagementsubnetprefix:
  hubvnetprefix:
  identitysubid:
  identitysubnetprefix:
  identityvnetprefix:  
  logaworkspaceid:
  managementsubid:
  managementsubnetprefix:
  managementvnetprefix:
  securitysubid:
  securitysubnetprefix:
  securityvnetprefix:
  

# Controls when the action will run. 
on:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
#  push:
#    branches:
#      - dev
#    paths:
#      - 'templates/entlz/platform-connectivity-vnethubspoke**'
#      - '.github/workflows/entlz-6a-platform-connectivity-vnethubspoke.yml'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
          
        steps:
        - uses: actions/checkout@v2
          with:
            ref: dev       
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Deploy Connectivity Components
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              bastionsubnetprefix="${{ env.bastionsubnetprefix }}"
              connectivitysubid="${{ env.connectivitysubid }}"
              entlzprefix="${{ env.entlzprefix }}"
              environment="${{ env.environment }}"
              fwmanagementsubnetprefix="${{ env.fwmanagementsubnetprefix }}"
              fwsubnetprefix="${{ env.fwsubnetprefix }}"
              fwtype="${{ env.fwtype }}"
              gwsubnetprefix="${{ env.gwsubnetprefix }}"
              gwtype="${{ env.gwtype }}"
              hubmanagementsubnetprefix="${{ env.hubmanagementsubnetprefix}}"
              hubvnetprefix="${{ env.hubvnetprefix }}"
              identitysubid="${{ env.identitysubid }}"
              identitysubnetprefix="${{ env.identitysubnetprefix }}"
              identityvnetprefix="${{ env.identityvnetprefix }}"
              location="${{ env.location }}"
              managementsubid="${{ env.managementsubid }}"
              managementsubnetprefix="${{ env.managementsubnetprefix }}"
              managementvnetprefix="${{ env.managementvnetprefix }}"
              securitysubid="${{ env.securitysubid }}"
              securitysubnetprefix="${{ env.securitysubnetprefix }}"
              securityvnetprefix="${{ env.securityvnetprefix }}"
              logaworkspaceid="${{ env.logaworkspaceid }}"

              az deployment mg create \
                  --name "${entlzprefix}-connectivity-${location}" \
                  --management-group-id $entlzprefix \
                  --location $location \
                  --template-file "templates/entlz/platform-connectivity-vnethubspoke/platform-connectivity-vnethubspoke.bicep" \
                  --parameters \
                    bastionsubnetprefix="${bastionsubnetprefix}" \
                    connectivitysubid="${connectivitysubid}" \
                    entlzprefix="${entlzprefix}" \
                    environment="${environment}" \
                    fwmanagementsubnetprefix="${fwmanagementsubnetprefix}" \
                    fwsubnetprefix="${fwsubnetprefix}" \
                    fwtype="${fwtype}" \
                    gwsubnetprefix="${gwsubnetprefix}" \
                    gwtype="${gwtype}" \
                    hubmanagementsubnetprefix="${hubmanagementsubnetprefix}" \
                    hubvnetprefix="${hubvnetprefix}" \
                    identitysubid="${identitysubid}" \
                    identitysubnetprefix="${identitysubnetprefix}" \
                    identityvnetprefix="${identityvnetprefix}" \
                    location="${location}" \
                    managementsubid="${managementsubid}" \
                    managementsubnetprefix="${managementsubnetprefix}" \
                    managementvnetprefix="${managementvnetprefix}" \
                    securitysubid="${securitysubid}" \
                    securitysubnetprefix="${securitysubnetprefix}" \
                    securityvnetprefix="${securityvnetprefix}" \
                    logaworkspaceid="${logaworkspaceid}"