name: entlz-1-platform-mgs



# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    env:
      ref: ${GITHUB_REF##*/}
      entlzprefix: entlz
      environment: azureusgovernment
      location: usgovvirginia

  repository_dispatch:
    types: [entlz-1-platform-mgs]
      env:
        ref: ${{ github.event.client_payload.ref }}
        entlzprefix: ${{ github.event.client_payload.entlz }}
        environment: ${{ github.event.client_payload.azureusgovernment }}
        location: ${{ github.event.client_payload.usgovvirginia }}
#  push:
#    branches:
#      - dev
#    paths:
#      - 'templates/entlz/platform-mgs.bicep'
#      - '.github/workflows/entlz-1-platform-mgs.yml'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.client_payload.ref }}
        - name: Branch name
          run: echo running on branch ${GITHUB_REF##*/}
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false

        - name: Deploy Management Groups
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
                # Deploy Management Groups using template

                az deployment tenant create \
                  --name "${{ env.entlzprefix }}-managementgroups-${{ env.location }}" \
                  --location ${{ env.location }} \
                  --template-file templates/entlz/platform-mgs.bicep \
                  --parameters entlzprefix=${{ env.entlzprefix }}
        
        - name: Configure Management Group Hierarchy Settings
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
                # Configure Management Group Hierarchy Settings

                TenantRootMG=$(az account management-group list --query "[0].name" --output tsv)
                resourceManagerURI=$(az cloud show --query 'endpoints.resourceManager' -o tsv)                
                az rest \
                  --method put \
                  --headers "{\"Content-Type\":\"application/json\"}" \
                  --uri "${resourceManagerURI}providers/Microsoft.Management/managementGroups/$TenantRootMG/settings/default?api-version=2020-05-01" \
                  --body "{\"properties\": {\"defaultManagementGroup\": \"/providers/Microsoft.Management/managementGroups/${{ env.entlzprefix }}-onboarding\",\"requireAuthorizationForGroupCreation\": \"true\"}}" 